### ISSUE TITLE
Errors and failing tests for included specs

### ISSUE THREAD

**Issue by johncaruso** [sn-developer/Spoke#1]
Just installed Spoke and while executing your included specs (for Spoke and Xplore), I'm getting errors and failing tests. Before I spent too much time debugging myself, I thought I'd report the issue. 

BTW, I wrote a SN server-side unit testing tool based on Jasmine back in 2013 (for an employer at the time) - dunno if the version of Rhino has improved much on the ES3 side (vs ES5 which definitely fixed many issues with the engine) , but I remember spending many hours debugging while trying to port Jasmine over. I share your pain if you ran into similar issues porting it. :-)

Nice to have an open source version that I can contribute to.

Here are some screenshots from my dev instance running Helsinki patch 1:

![2016-09-29 3](https://cloud.githubusercontent.com/assets/224397/18968581/33c43736-864f-11e6-9b17-f9311c3d5e8b.png)
![2016-09-29 5](https://cloud.githubusercontent.com/assets/224397/18968583/33c9cb88-864f-11e6-9a98-64b53e464039.png)

**Comment by jneale** [comment]
Hey John, great to see some feedback on this. Thanks! I've made a whole load of improvements and fixed a whole lot of stuff since this version, just need to release which I may well do tonight now you've reminded me. Cheers

**Comment by johncaruso** [comment]
New version resolved these errors, thanks!
